name: runner

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        shard: [0]

    steps:
      - name: runner
        run: |
          cd
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/local/.ghcup
          df -h
          free -h
